// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFoxSymbol = "fox_symbols"

// FoxSymbol symbol table
type FoxSymbol struct {
	ID         int64      `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true;comment:symbol id" json:"id"`                         // symbol id
	Name       string     `gorm:"column:name;type:varchar(100);not null;comment:name" json:"name"`                                                   // name
	AccountID  int64      `gorm:"column:account_id;type:int(11);not null;comment:user id" json:"account_id"`                                         // user id
	Exchange   string     `gorm:"column:exchange;type:enum('okx','binance','gate');not null;default:okx;comment:exchange" json:"exchange"`           // exchange
	Leverage   int64      `gorm:"column:leverage;type:int(11);not null;comment:leverage" json:"leverage"`                                            // leverage
	MarginType string     `gorm:"column:margin_type;type:enum('isolated','cross');not null;default:isolated;comment:margin type" json:"margin_type"` // margin type
	CreatedAt  time.Time  `gorm:"column:created_at;type:timestamp;default:current_timestamp();comment:create time" json:"created_at"`                // create time
	UpdatedAt  time.Time  `gorm:"column:updated_at;type:timestamp;default:current_timestamp();comment:update time" json:"updated_at"`                // update time
	Account    FoxAccount `gorm:"foreignKey:account_id;references:id" json:"account"`
}

// TableName FoxSymbol's table name
func (*FoxSymbol) TableName() string {
	return TableNameFoxSymbol
}
