// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFoxExchange = "fox_exchanges"

// FoxExchange exchange table
type FoxExchange struct {
	ID        int64     `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true;comment:exchange id" json:"id"`        // exchange id
	Name      string    `gorm:"column:name;type:varchar(100);not null;comment:name" json:"name"`                                    // name
	APIURL    string    `gorm:"column:api_url;type:varchar(512);not null;comment:api url" json:"api_url"`                           // api url
	ProxyURL  string    `gorm:"column:proxy_url;type:varchar(100);not null;comment:proxy url" json:"proxy_url"`                     // proxy url
	IsActive  int       `gorm:"column:is_active;type:tinyint(1);not null;comment:active status" json:"is_active"`                   // active status
	CreatedAt time.Time `gorm:"column:created_at;type:timestamp;default:current_timestamp();comment:create time" json:"created_at"` // create time
	UpdatedAt time.Time `gorm:"column:updated_at;type:timestamp;default:current_timestamp();comment:update time" json:"updated_at"` // update time
}

// TableName FoxExchange's table name
func (*FoxExchange) TableName() string {
	return TableNameFoxExchange
}
