// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFoxOrder = "fox_orders"

// FoxOrder mapped from table <fox_orders>
type FoxOrder struct {
	ID         int64      `gorm:"column:id;type:integer;primaryKey" json:"id"`
	Exchange   string     `gorm:"column:exchange;type:text;not null;default:okx" json:"exchange"`
	AccountID  int64      `gorm:"column:account_id;type:integer;not null" json:"account_id"`
	Symbol     string     `gorm:"column:symbol;type:text;not null" json:"symbol"`
	Side       string     `gorm:"column:side;type:text;not null" json:"side"`
	PosSide    string     `gorm:"column:pos_side;type:text;not null" json:"pos_side"`
	MarginType string     `gorm:"column:margin_type;type:text;not null" json:"margin_type"`
	Price      string     `gorm:"column:price;type:text;not null" json:"price"`
	Size       string     `gorm:"column:size;type:text;not null" json:"size"`
	SizeType   string     `gorm:"column:size_type;type:text;not null" json:"size_type"`
	OrderType  string     `gorm:"column:order_type;type:text;not null;default:limit" json:"order_type"`
	Strategy   string     `gorm:"column:strategy;type:text;not null" json:"strategy"`
	OrderID    string     `gorm:"column:order_id;type:text;not null" json:"order_id"`
	Type       string     `gorm:"column:type;type:text;not null;default:open" json:"type"`
	Status     string     `gorm:"column:status;type:text;not null;default:waiting" json:"status"`
	Msg        string     `gorm:"column:msg;type:text;not null" json:"msg"`
	CreatedAt  string     `gorm:"column:created_at;type:text;not null" json:"created_at"`
	UpdatedAt  string     `gorm:"column:updated_at;type:text;not null" json:"updated_at"`
	Account    FoxAccount `gorm:"foreignKey:account_id;references:id" json:"account"`
}

// TableName FoxOrder's table name
func (*FoxOrder) TableName() string {
	return TableNameFoxOrder
}
