// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFoxExchange = "fox_exchanges"

// FoxExchange mapped from table <fox_exchanges>
type FoxExchange struct {
	ID        int64  `gorm:"column:id;type:integer;primaryKey" json:"id"`
	Name      string `gorm:"column:name;type:text;not null" json:"name"`
	APIURL    string `gorm:"column:api_url;type:text;not null" json:"api_url"`
	ProxyURL  string `gorm:"column:proxy_url;type:text;not null" json:"proxy_url"`
	IsActive  int64  `gorm:"column:is_active;type:integer;not null" json:"is_active"`
	CreatedAt string `gorm:"column:created_at;type:text;not null" json:"created_at"`
	UpdatedAt string `gorm:"column:updated_at;type:text;not null" json:"updated_at"`
}

// TableName FoxExchange's table name
func (*FoxExchange) TableName() string {
	return TableNameFoxExchange
}
