// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFoxSymbol = "fox_symbols"

// FoxSymbol mapped from table <fox_symbols>
type FoxSymbol struct {
	ID         int64      `gorm:"column:id;type:integer;primaryKey" json:"id"`
	Name       string     `gorm:"column:name;type:text;not null" json:"name"`
	AccountID  int64      `gorm:"column:account_id;type:integer;not null" json:"account_id"`
	Exchange   string     `gorm:"column:exchange;type:text;not null;default:okx" json:"exchange"`
	Leverage   int64      `gorm:"column:leverage;type:integer;not null;default:1" json:"leverage"`
	MarginType string     `gorm:"column:margin_type;type:text;not null;default:isolated" json:"margin_type"`
	CreatedAt  string     `gorm:"column:created_at;type:text;not null" json:"created_at"`
	UpdatedAt  string     `gorm:"column:updated_at;type:text;not null" json:"updated_at"`
	Account    FoxAccount `gorm:"foreignKey:account_id;references:id" json:"account"`
}

// TableName FoxSymbol's table name
func (*FoxSymbol) TableName() string {
	return TableNameFoxSymbol
}
