// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFoxTradeConfig = "fox_trade_configs"

// FoxTradeConfig mapped from table <fox_trade_configs>
type FoxTradeConfig struct {
	ID        int64     `gorm:"column:id;type:integer;primaryKey" json:"id"`
	AccountID int64     `gorm:"column:account_id;type:integer;not null" json:"account_id"`
	Margin    string    `gorm:"column:margin;type:text;not null" json:"margin"`
	Leverage  int64     `gorm:"column:leverage;type:integer;not null" json:"leverage"`
	CreatedAt time.Time `gorm:"column:created_at;type:datetime" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;type:datetime" json:"updated_at"`
}

// TableName FoxTradeConfig's table name
func (*FoxTradeConfig) TableName() string {
	return TableNameFoxTradeConfig
}
