// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFoxConfig = "fox_configs"

// FoxConfig mapped from table <fox_configs>
type FoxConfig struct {
	ID        int64     `gorm:"column:id;type:integer;primaryKey" json:"id"`
	AccountID int64     `gorm:"column:account_id;type:integer;not null" json:"account_id"`
	ProxyURL  string    `gorm:"column:proxy_url;type:text;not null" json:"proxy_url"`
	CreatedAt time.Time `gorm:"column:created_at;type:datetime" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;type:datetime" json:"updated_at"`
}

// TableName FoxConfig's table name
func (*FoxConfig) TableName() string {
	return TableNameFoxConfig
}
