// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSystemInfo = "system_infos"

// SystemInfo mapped from table <system_infos>
type SystemInfo struct {
	ID      int64  `gorm:"column:id;type:integer;primaryKey" json:"id"`
	DbUUID  string `gorm:"column:db_uuid;type:text" json:"db_uuid"`
	Version string `gorm:"column:version;type:text" json:"version"`
	UUID    string `gorm:"column:uuid;type:text" json:"uuid"`
}

// TableName SystemInfo's table name
func (*SystemInfo) TableName() string {
	return TableNameSystemInfo
}
