// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/lemconn/foxflow/internal/pkg/dao/model"
)

func newFoxConfig(db *gorm.DB, opts ...gen.DOOption) foxConfig {
	_foxConfig := foxConfig{}

	_foxConfig.foxConfigDo.UseDB(db, opts...)
	_foxConfig.foxConfigDo.UseModel(&model.FoxConfig{})

	tableName := _foxConfig.foxConfigDo.TableName()
	_foxConfig.ALL = field.NewAsterisk(tableName)
	_foxConfig.ID = field.NewInt64(tableName, "id")
	_foxConfig.AccountID = field.NewInt64(tableName, "account_id")
	_foxConfig.ProxyURL = field.NewString(tableName, "proxy_url")
	_foxConfig.CreatedAt = field.NewTime(tableName, "created_at")
	_foxConfig.UpdatedAt = field.NewTime(tableName, "updated_at")

	_foxConfig.fillFieldMap()

	return _foxConfig
}

type foxConfig struct {
	foxConfigDo

	ALL       field.Asterisk
	ID        field.Int64
	AccountID field.Int64
	ProxyURL  field.String
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (f foxConfig) Table(newTableName string) *foxConfig {
	f.foxConfigDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f foxConfig) As(alias string) *foxConfig {
	f.foxConfigDo.DO = *(f.foxConfigDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *foxConfig) updateTableName(table string) *foxConfig {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewInt64(table, "id")
	f.AccountID = field.NewInt64(table, "account_id")
	f.ProxyURL = field.NewString(table, "proxy_url")
	f.CreatedAt = field.NewTime(table, "created_at")
	f.UpdatedAt = field.NewTime(table, "updated_at")

	f.fillFieldMap()

	return f
}

func (f *foxConfig) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *foxConfig) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 5)
	f.fieldMap["id"] = f.ID
	f.fieldMap["account_id"] = f.AccountID
	f.fieldMap["proxy_url"] = f.ProxyURL
	f.fieldMap["created_at"] = f.CreatedAt
	f.fieldMap["updated_at"] = f.UpdatedAt
}

func (f foxConfig) clone(db *gorm.DB) foxConfig {
	f.foxConfigDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f foxConfig) replaceDB(db *gorm.DB) foxConfig {
	f.foxConfigDo.ReplaceDB(db)
	return f
}

type foxConfigDo struct{ gen.DO }

type IFoxConfigDo interface {
	gen.SubQuery
	Debug() IFoxConfigDo
	WithContext(ctx context.Context) IFoxConfigDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IFoxConfigDo
	WriteDB() IFoxConfigDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IFoxConfigDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IFoxConfigDo
	Not(conds ...gen.Condition) IFoxConfigDo
	Or(conds ...gen.Condition) IFoxConfigDo
	Select(conds ...field.Expr) IFoxConfigDo
	Where(conds ...gen.Condition) IFoxConfigDo
	Order(conds ...field.Expr) IFoxConfigDo
	Distinct(cols ...field.Expr) IFoxConfigDo
	Omit(cols ...field.Expr) IFoxConfigDo
	Join(table schema.Tabler, on ...field.Expr) IFoxConfigDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IFoxConfigDo
	RightJoin(table schema.Tabler, on ...field.Expr) IFoxConfigDo
	Group(cols ...field.Expr) IFoxConfigDo
	Having(conds ...gen.Condition) IFoxConfigDo
	Limit(limit int) IFoxConfigDo
	Offset(offset int) IFoxConfigDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IFoxConfigDo
	Unscoped() IFoxConfigDo
	Create(values ...*model.FoxConfig) error
	CreateInBatches(values []*model.FoxConfig, batchSize int) error
	Save(values ...*model.FoxConfig) error
	First() (*model.FoxConfig, error)
	Take() (*model.FoxConfig, error)
	Last() (*model.FoxConfig, error)
	Find() ([]*model.FoxConfig, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FoxConfig, err error)
	FindInBatches(result *[]*model.FoxConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.FoxConfig) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IFoxConfigDo
	Assign(attrs ...field.AssignExpr) IFoxConfigDo
	Joins(fields ...field.RelationField) IFoxConfigDo
	Preload(fields ...field.RelationField) IFoxConfigDo
	FirstOrInit() (*model.FoxConfig, error)
	FirstOrCreate() (*model.FoxConfig, error)
	FindByPage(offset int, limit int) (result []*model.FoxConfig, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IFoxConfigDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (f foxConfigDo) Debug() IFoxConfigDo {
	return f.withDO(f.DO.Debug())
}

func (f foxConfigDo) WithContext(ctx context.Context) IFoxConfigDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f foxConfigDo) ReadDB() IFoxConfigDo {
	return f.Clauses(dbresolver.Read)
}

func (f foxConfigDo) WriteDB() IFoxConfigDo {
	return f.Clauses(dbresolver.Write)
}

func (f foxConfigDo) Session(config *gorm.Session) IFoxConfigDo {
	return f.withDO(f.DO.Session(config))
}

func (f foxConfigDo) Clauses(conds ...clause.Expression) IFoxConfigDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f foxConfigDo) Returning(value interface{}, columns ...string) IFoxConfigDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f foxConfigDo) Not(conds ...gen.Condition) IFoxConfigDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f foxConfigDo) Or(conds ...gen.Condition) IFoxConfigDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f foxConfigDo) Select(conds ...field.Expr) IFoxConfigDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f foxConfigDo) Where(conds ...gen.Condition) IFoxConfigDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f foxConfigDo) Order(conds ...field.Expr) IFoxConfigDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f foxConfigDo) Distinct(cols ...field.Expr) IFoxConfigDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f foxConfigDo) Omit(cols ...field.Expr) IFoxConfigDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f foxConfigDo) Join(table schema.Tabler, on ...field.Expr) IFoxConfigDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f foxConfigDo) LeftJoin(table schema.Tabler, on ...field.Expr) IFoxConfigDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f foxConfigDo) RightJoin(table schema.Tabler, on ...field.Expr) IFoxConfigDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f foxConfigDo) Group(cols ...field.Expr) IFoxConfigDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f foxConfigDo) Having(conds ...gen.Condition) IFoxConfigDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f foxConfigDo) Limit(limit int) IFoxConfigDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f foxConfigDo) Offset(offset int) IFoxConfigDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f foxConfigDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IFoxConfigDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f foxConfigDo) Unscoped() IFoxConfigDo {
	return f.withDO(f.DO.Unscoped())
}

func (f foxConfigDo) Create(values ...*model.FoxConfig) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f foxConfigDo) CreateInBatches(values []*model.FoxConfig, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f foxConfigDo) Save(values ...*model.FoxConfig) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f foxConfigDo) First() (*model.FoxConfig, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.FoxConfig), nil
	}
}

func (f foxConfigDo) Take() (*model.FoxConfig, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.FoxConfig), nil
	}
}

func (f foxConfigDo) Last() (*model.FoxConfig, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.FoxConfig), nil
	}
}

func (f foxConfigDo) Find() ([]*model.FoxConfig, error) {
	result, err := f.DO.Find()
	return result.([]*model.FoxConfig), err
}

func (f foxConfigDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FoxConfig, err error) {
	buf := make([]*model.FoxConfig, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f foxConfigDo) FindInBatches(result *[]*model.FoxConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f foxConfigDo) Attrs(attrs ...field.AssignExpr) IFoxConfigDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f foxConfigDo) Assign(attrs ...field.AssignExpr) IFoxConfigDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f foxConfigDo) Joins(fields ...field.RelationField) IFoxConfigDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f foxConfigDo) Preload(fields ...field.RelationField) IFoxConfigDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f foxConfigDo) FirstOrInit() (*model.FoxConfig, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.FoxConfig), nil
	}
}

func (f foxConfigDo) FirstOrCreate() (*model.FoxConfig, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.FoxConfig), nil
	}
}

func (f foxConfigDo) FindByPage(offset int, limit int) (result []*model.FoxConfig, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f foxConfigDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f foxConfigDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f foxConfigDo) Delete(models ...*model.FoxConfig) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *foxConfigDo) withDO(do gen.Dao) *foxConfigDo {
	f.DO = *do.(*gen.DO)
	return f
}
