// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/lemconn/foxflow/internal/pkg/dao/model"
)

func newFoxTradeConfig(db *gorm.DB, opts ...gen.DOOption) foxTradeConfig {
	_foxTradeConfig := foxTradeConfig{}

	_foxTradeConfig.foxTradeConfigDo.UseDB(db, opts...)
	_foxTradeConfig.foxTradeConfigDo.UseModel(&model.FoxTradeConfig{})

	tableName := _foxTradeConfig.foxTradeConfigDo.TableName()
	_foxTradeConfig.ALL = field.NewAsterisk(tableName)
	_foxTradeConfig.ID = field.NewInt64(tableName, "id")
	_foxTradeConfig.AccountID = field.NewInt64(tableName, "account_id")
	_foxTradeConfig.Margin = field.NewString(tableName, "margin")
	_foxTradeConfig.Leverage = field.NewInt64(tableName, "leverage")
	_foxTradeConfig.CreatedAt = field.NewTime(tableName, "created_at")
	_foxTradeConfig.UpdatedAt = field.NewTime(tableName, "updated_at")

	_foxTradeConfig.fillFieldMap()

	return _foxTradeConfig
}

type foxTradeConfig struct {
	foxTradeConfigDo

	ALL       field.Asterisk
	ID        field.Int64
	AccountID field.Int64
	Margin    field.String
	Leverage  field.Int64
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (f foxTradeConfig) Table(newTableName string) *foxTradeConfig {
	f.foxTradeConfigDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f foxTradeConfig) As(alias string) *foxTradeConfig {
	f.foxTradeConfigDo.DO = *(f.foxTradeConfigDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *foxTradeConfig) updateTableName(table string) *foxTradeConfig {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewInt64(table, "id")
	f.AccountID = field.NewInt64(table, "account_id")
	f.Margin = field.NewString(table, "margin")
	f.Leverage = field.NewInt64(table, "leverage")
	f.CreatedAt = field.NewTime(table, "created_at")
	f.UpdatedAt = field.NewTime(table, "updated_at")

	f.fillFieldMap()

	return f
}

func (f *foxTradeConfig) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *foxTradeConfig) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 6)
	f.fieldMap["id"] = f.ID
	f.fieldMap["account_id"] = f.AccountID
	f.fieldMap["margin"] = f.Margin
	f.fieldMap["leverage"] = f.Leverage
	f.fieldMap["created_at"] = f.CreatedAt
	f.fieldMap["updated_at"] = f.UpdatedAt
}

func (f foxTradeConfig) clone(db *gorm.DB) foxTradeConfig {
	f.foxTradeConfigDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f foxTradeConfig) replaceDB(db *gorm.DB) foxTradeConfig {
	f.foxTradeConfigDo.ReplaceDB(db)
	return f
}

type foxTradeConfigDo struct{ gen.DO }

type IFoxTradeConfigDo interface {
	gen.SubQuery
	Debug() IFoxTradeConfigDo
	WithContext(ctx context.Context) IFoxTradeConfigDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IFoxTradeConfigDo
	WriteDB() IFoxTradeConfigDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IFoxTradeConfigDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IFoxTradeConfigDo
	Not(conds ...gen.Condition) IFoxTradeConfigDo
	Or(conds ...gen.Condition) IFoxTradeConfigDo
	Select(conds ...field.Expr) IFoxTradeConfigDo
	Where(conds ...gen.Condition) IFoxTradeConfigDo
	Order(conds ...field.Expr) IFoxTradeConfigDo
	Distinct(cols ...field.Expr) IFoxTradeConfigDo
	Omit(cols ...field.Expr) IFoxTradeConfigDo
	Join(table schema.Tabler, on ...field.Expr) IFoxTradeConfigDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IFoxTradeConfigDo
	RightJoin(table schema.Tabler, on ...field.Expr) IFoxTradeConfigDo
	Group(cols ...field.Expr) IFoxTradeConfigDo
	Having(conds ...gen.Condition) IFoxTradeConfigDo
	Limit(limit int) IFoxTradeConfigDo
	Offset(offset int) IFoxTradeConfigDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IFoxTradeConfigDo
	Unscoped() IFoxTradeConfigDo
	Create(values ...*model.FoxTradeConfig) error
	CreateInBatches(values []*model.FoxTradeConfig, batchSize int) error
	Save(values ...*model.FoxTradeConfig) error
	First() (*model.FoxTradeConfig, error)
	Take() (*model.FoxTradeConfig, error)
	Last() (*model.FoxTradeConfig, error)
	Find() ([]*model.FoxTradeConfig, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FoxTradeConfig, err error)
	FindInBatches(result *[]*model.FoxTradeConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.FoxTradeConfig) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IFoxTradeConfigDo
	Assign(attrs ...field.AssignExpr) IFoxTradeConfigDo
	Joins(fields ...field.RelationField) IFoxTradeConfigDo
	Preload(fields ...field.RelationField) IFoxTradeConfigDo
	FirstOrInit() (*model.FoxTradeConfig, error)
	FirstOrCreate() (*model.FoxTradeConfig, error)
	FindByPage(offset int, limit int) (result []*model.FoxTradeConfig, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IFoxTradeConfigDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (f foxTradeConfigDo) Debug() IFoxTradeConfigDo {
	return f.withDO(f.DO.Debug())
}

func (f foxTradeConfigDo) WithContext(ctx context.Context) IFoxTradeConfigDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f foxTradeConfigDo) ReadDB() IFoxTradeConfigDo {
	return f.Clauses(dbresolver.Read)
}

func (f foxTradeConfigDo) WriteDB() IFoxTradeConfigDo {
	return f.Clauses(dbresolver.Write)
}

func (f foxTradeConfigDo) Session(config *gorm.Session) IFoxTradeConfigDo {
	return f.withDO(f.DO.Session(config))
}

func (f foxTradeConfigDo) Clauses(conds ...clause.Expression) IFoxTradeConfigDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f foxTradeConfigDo) Returning(value interface{}, columns ...string) IFoxTradeConfigDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f foxTradeConfigDo) Not(conds ...gen.Condition) IFoxTradeConfigDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f foxTradeConfigDo) Or(conds ...gen.Condition) IFoxTradeConfigDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f foxTradeConfigDo) Select(conds ...field.Expr) IFoxTradeConfigDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f foxTradeConfigDo) Where(conds ...gen.Condition) IFoxTradeConfigDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f foxTradeConfigDo) Order(conds ...field.Expr) IFoxTradeConfigDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f foxTradeConfigDo) Distinct(cols ...field.Expr) IFoxTradeConfigDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f foxTradeConfigDo) Omit(cols ...field.Expr) IFoxTradeConfigDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f foxTradeConfigDo) Join(table schema.Tabler, on ...field.Expr) IFoxTradeConfigDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f foxTradeConfigDo) LeftJoin(table schema.Tabler, on ...field.Expr) IFoxTradeConfigDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f foxTradeConfigDo) RightJoin(table schema.Tabler, on ...field.Expr) IFoxTradeConfigDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f foxTradeConfigDo) Group(cols ...field.Expr) IFoxTradeConfigDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f foxTradeConfigDo) Having(conds ...gen.Condition) IFoxTradeConfigDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f foxTradeConfigDo) Limit(limit int) IFoxTradeConfigDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f foxTradeConfigDo) Offset(offset int) IFoxTradeConfigDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f foxTradeConfigDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IFoxTradeConfigDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f foxTradeConfigDo) Unscoped() IFoxTradeConfigDo {
	return f.withDO(f.DO.Unscoped())
}

func (f foxTradeConfigDo) Create(values ...*model.FoxTradeConfig) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f foxTradeConfigDo) CreateInBatches(values []*model.FoxTradeConfig, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f foxTradeConfigDo) Save(values ...*model.FoxTradeConfig) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f foxTradeConfigDo) First() (*model.FoxTradeConfig, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.FoxTradeConfig), nil
	}
}

func (f foxTradeConfigDo) Take() (*model.FoxTradeConfig, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.FoxTradeConfig), nil
	}
}

func (f foxTradeConfigDo) Last() (*model.FoxTradeConfig, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.FoxTradeConfig), nil
	}
}

func (f foxTradeConfigDo) Find() ([]*model.FoxTradeConfig, error) {
	result, err := f.DO.Find()
	return result.([]*model.FoxTradeConfig), err
}

func (f foxTradeConfigDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FoxTradeConfig, err error) {
	buf := make([]*model.FoxTradeConfig, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f foxTradeConfigDo) FindInBatches(result *[]*model.FoxTradeConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f foxTradeConfigDo) Attrs(attrs ...field.AssignExpr) IFoxTradeConfigDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f foxTradeConfigDo) Assign(attrs ...field.AssignExpr) IFoxTradeConfigDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f foxTradeConfigDo) Joins(fields ...field.RelationField) IFoxTradeConfigDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f foxTradeConfigDo) Preload(fields ...field.RelationField) IFoxTradeConfigDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f foxTradeConfigDo) FirstOrInit() (*model.FoxTradeConfig, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.FoxTradeConfig), nil
	}
}

func (f foxTradeConfigDo) FirstOrCreate() (*model.FoxTradeConfig, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.FoxTradeConfig), nil
	}
}

func (f foxTradeConfigDo) FindByPage(offset int, limit int) (result []*model.FoxTradeConfig, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f foxTradeConfigDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f foxTradeConfigDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f foxTradeConfigDo) Delete(models ...*model.FoxTradeConfig) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *foxTradeConfigDo) withDO(do gen.Dao) *foxTradeConfigDo {
	f.DO = *do.(*gen.DO)
	return f
}
