// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q              = new(Query)
	FoxAccount     *foxAccount
	FoxExchange    *foxExchange
	FoxOrder       *foxOrder
	FoxSymbol      *foxSymbol
	SqliteSequence *sqliteSequence
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	FoxAccount = &Q.FoxAccount
	FoxExchange = &Q.FoxExchange
	FoxOrder = &Q.FoxOrder
	FoxSymbol = &Q.FoxSymbol
	SqliteSequence = &Q.SqliteSequence
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:             db,
		FoxAccount:     newFoxAccount(db, opts...),
		FoxExchange:    newFoxExchange(db, opts...),
		FoxOrder:       newFoxOrder(db, opts...),
		FoxSymbol:      newFoxSymbol(db, opts...),
		SqliteSequence: newSqliteSequence(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	FoxAccount     foxAccount
	FoxExchange    foxExchange
	FoxOrder       foxOrder
	FoxSymbol      foxSymbol
	SqliteSequence sqliteSequence
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:             db,
		FoxAccount:     q.FoxAccount.clone(db),
		FoxExchange:    q.FoxExchange.clone(db),
		FoxOrder:       q.FoxOrder.clone(db),
		FoxSymbol:      q.FoxSymbol.clone(db),
		SqliteSequence: q.SqliteSequence.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:             db,
		FoxAccount:     q.FoxAccount.replaceDB(db),
		FoxExchange:    q.FoxExchange.replaceDB(db),
		FoxOrder:       q.FoxOrder.replaceDB(db),
		FoxSymbol:      q.FoxSymbol.replaceDB(db),
		SqliteSequence: q.SqliteSequence.replaceDB(db),
	}
}

type queryCtx struct {
	FoxAccount     IFoxAccountDo
	FoxExchange    IFoxExchangeDo
	FoxOrder       IFoxOrderDo
	FoxSymbol      IFoxSymbolDo
	SqliteSequence ISqliteSequenceDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		FoxAccount:     q.FoxAccount.WithContext(ctx),
		FoxExchange:    q.FoxExchange.WithContext(ctx),
		FoxOrder:       q.FoxOrder.WithContext(ctx),
		FoxSymbol:      q.FoxSymbol.WithContext(ctx),
		SqliteSequence: q.SqliteSequence.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
