// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/lemconn/foxflow/internal/pkg/dao/model"
)

func newSystemInfo(db *gorm.DB, opts ...gen.DOOption) systemInfo {
	_systemInfo := systemInfo{}

	_systemInfo.systemInfoDo.UseDB(db, opts...)
	_systemInfo.systemInfoDo.UseModel(&model.SystemInfo{})

	tableName := _systemInfo.systemInfoDo.TableName()
	_systemInfo.ALL = field.NewAsterisk(tableName)
	_systemInfo.ID = field.NewInt64(tableName, "id")
	_systemInfo.DbUUID = field.NewString(tableName, "db_uuid")
	_systemInfo.Version = field.NewString(tableName, "version")
	_systemInfo.UUID = field.NewString(tableName, "uuid")

	_systemInfo.fillFieldMap()

	return _systemInfo
}

type systemInfo struct {
	systemInfoDo

	ALL     field.Asterisk
	ID      field.Int64
	DbUUID  field.String
	Version field.String
	UUID    field.String

	fieldMap map[string]field.Expr
}

func (s systemInfo) Table(newTableName string) *systemInfo {
	s.systemInfoDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s systemInfo) As(alias string) *systemInfo {
	s.systemInfoDo.DO = *(s.systemInfoDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *systemInfo) updateTableName(table string) *systemInfo {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.DbUUID = field.NewString(table, "db_uuid")
	s.Version = field.NewString(table, "version")
	s.UUID = field.NewString(table, "uuid")

	s.fillFieldMap()

	return s
}

func (s *systemInfo) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *systemInfo) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 4)
	s.fieldMap["id"] = s.ID
	s.fieldMap["db_uuid"] = s.DbUUID
	s.fieldMap["version"] = s.Version
	s.fieldMap["uuid"] = s.UUID
}

func (s systemInfo) clone(db *gorm.DB) systemInfo {
	s.systemInfoDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s systemInfo) replaceDB(db *gorm.DB) systemInfo {
	s.systemInfoDo.ReplaceDB(db)
	return s
}

type systemInfoDo struct{ gen.DO }

type ISystemInfoDo interface {
	gen.SubQuery
	Debug() ISystemInfoDo
	WithContext(ctx context.Context) ISystemInfoDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISystemInfoDo
	WriteDB() ISystemInfoDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISystemInfoDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISystemInfoDo
	Not(conds ...gen.Condition) ISystemInfoDo
	Or(conds ...gen.Condition) ISystemInfoDo
	Select(conds ...field.Expr) ISystemInfoDo
	Where(conds ...gen.Condition) ISystemInfoDo
	Order(conds ...field.Expr) ISystemInfoDo
	Distinct(cols ...field.Expr) ISystemInfoDo
	Omit(cols ...field.Expr) ISystemInfoDo
	Join(table schema.Tabler, on ...field.Expr) ISystemInfoDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISystemInfoDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISystemInfoDo
	Group(cols ...field.Expr) ISystemInfoDo
	Having(conds ...gen.Condition) ISystemInfoDo
	Limit(limit int) ISystemInfoDo
	Offset(offset int) ISystemInfoDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISystemInfoDo
	Unscoped() ISystemInfoDo
	Create(values ...*model.SystemInfo) error
	CreateInBatches(values []*model.SystemInfo, batchSize int) error
	Save(values ...*model.SystemInfo) error
	First() (*model.SystemInfo, error)
	Take() (*model.SystemInfo, error)
	Last() (*model.SystemInfo, error)
	Find() ([]*model.SystemInfo, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SystemInfo, err error)
	FindInBatches(result *[]*model.SystemInfo, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SystemInfo) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISystemInfoDo
	Assign(attrs ...field.AssignExpr) ISystemInfoDo
	Joins(fields ...field.RelationField) ISystemInfoDo
	Preload(fields ...field.RelationField) ISystemInfoDo
	FirstOrInit() (*model.SystemInfo, error)
	FirstOrCreate() (*model.SystemInfo, error)
	FindByPage(offset int, limit int) (result []*model.SystemInfo, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISystemInfoDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s systemInfoDo) Debug() ISystemInfoDo {
	return s.withDO(s.DO.Debug())
}

func (s systemInfoDo) WithContext(ctx context.Context) ISystemInfoDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s systemInfoDo) ReadDB() ISystemInfoDo {
	return s.Clauses(dbresolver.Read)
}

func (s systemInfoDo) WriteDB() ISystemInfoDo {
	return s.Clauses(dbresolver.Write)
}

func (s systemInfoDo) Session(config *gorm.Session) ISystemInfoDo {
	return s.withDO(s.DO.Session(config))
}

func (s systemInfoDo) Clauses(conds ...clause.Expression) ISystemInfoDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s systemInfoDo) Returning(value interface{}, columns ...string) ISystemInfoDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s systemInfoDo) Not(conds ...gen.Condition) ISystemInfoDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s systemInfoDo) Or(conds ...gen.Condition) ISystemInfoDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s systemInfoDo) Select(conds ...field.Expr) ISystemInfoDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s systemInfoDo) Where(conds ...gen.Condition) ISystemInfoDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s systemInfoDo) Order(conds ...field.Expr) ISystemInfoDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s systemInfoDo) Distinct(cols ...field.Expr) ISystemInfoDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s systemInfoDo) Omit(cols ...field.Expr) ISystemInfoDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s systemInfoDo) Join(table schema.Tabler, on ...field.Expr) ISystemInfoDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s systemInfoDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISystemInfoDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s systemInfoDo) RightJoin(table schema.Tabler, on ...field.Expr) ISystemInfoDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s systemInfoDo) Group(cols ...field.Expr) ISystemInfoDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s systemInfoDo) Having(conds ...gen.Condition) ISystemInfoDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s systemInfoDo) Limit(limit int) ISystemInfoDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s systemInfoDo) Offset(offset int) ISystemInfoDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s systemInfoDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISystemInfoDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s systemInfoDo) Unscoped() ISystemInfoDo {
	return s.withDO(s.DO.Unscoped())
}

func (s systemInfoDo) Create(values ...*model.SystemInfo) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s systemInfoDo) CreateInBatches(values []*model.SystemInfo, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s systemInfoDo) Save(values ...*model.SystemInfo) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s systemInfoDo) First() (*model.SystemInfo, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemInfo), nil
	}
}

func (s systemInfoDo) Take() (*model.SystemInfo, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemInfo), nil
	}
}

func (s systemInfoDo) Last() (*model.SystemInfo, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemInfo), nil
	}
}

func (s systemInfoDo) Find() ([]*model.SystemInfo, error) {
	result, err := s.DO.Find()
	return result.([]*model.SystemInfo), err
}

func (s systemInfoDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SystemInfo, err error) {
	buf := make([]*model.SystemInfo, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s systemInfoDo) FindInBatches(result *[]*model.SystemInfo, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s systemInfoDo) Attrs(attrs ...field.AssignExpr) ISystemInfoDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s systemInfoDo) Assign(attrs ...field.AssignExpr) ISystemInfoDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s systemInfoDo) Joins(fields ...field.RelationField) ISystemInfoDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s systemInfoDo) Preload(fields ...field.RelationField) ISystemInfoDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s systemInfoDo) FirstOrInit() (*model.SystemInfo, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemInfo), nil
	}
}

func (s systemInfoDo) FirstOrCreate() (*model.SystemInfo, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemInfo), nil
	}
}

func (s systemInfoDo) FindByPage(offset int, limit int) (result []*model.SystemInfo, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s systemInfoDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s systemInfoDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s systemInfoDo) Delete(models ...*model.SystemInfo) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *systemInfoDo) withDO(do gen.Dao) *systemInfoDo {
	s.DO = *do.(*gen.DO)
	return s
}
