name: Run Go Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Show Go version
        run: go version

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          echo "GOPATH=$(go env GOPATH)"
          echo "${{ runner.temp }}"
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          which protoc
          which protoc-gen-go
          which protoc-gen-go-grpc
          protoc --version
          protoc-gen-go --version
          protoc-gen-go-grpc --version

      - name: Run build
        run: make build

      - name: Run unit tests
        run: make test
